[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:all"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/debug"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
